# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - develop

pool:
  vmImage: "ubuntu-latest"

variables:
  ${{ if or(eq(variables['Build.SourceBranchName'], 'develop'), endsWith(variables['System.PullRequest.TargetBranch'], 'develop') ) }}:
    STACK: dev
  ${{if or(eq(variables['Build.SourceBranchName'], 'master'), endsWith(variables['System.PullRequest.TargetBranch'], 'master') ) }}:
    STACK: prod
  


stages:
  - stage: preview
    displayName: Preview infra
    variables:
      - group: common
    jobs:
      - job: previewInfra
        displayName: Preview infra (pulumi)
        cancelTimeoutInMinutes: 7
        steps:
          - script: echo ${{variables.STACK}}
          - task: Npm@1
            displayName: Pulumi npm install
            inputs:
              command: install
          - task: Pulumi@1
            displayName: Pulumi infra preview
            inputs:
              azureSubscription: "Azure thesis resource manager"
              command: "preview"
              stack: ${{variables.STACK}}

  - stage: deploy
    displayName: Apply infra (pulumi up)
    dependsOn: preview
    variables:
      - group: common
    jobs:
      - deployment: deployFrontendAndBackend
        displayName: Deploy frontend and backend
        environment: dev
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - script: |
                    ls
                    cd scripts
                    ls
                - script: |
                    chmod +x ./scripts/*.sh
                    ./scripts/run-pulumi.sh
                  displayName: "Install pulumi and run pulumi up"
                  name: pulumi
                  env:
                    PULUMI_ACCESS_TOKEN: $(PULUMI_ACCESS_TOKEN)
                    ARM_CLIENT_ID: $(ARM_CLIENT_ID)
                    ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
                    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
                    ARM_TENANT_ID: $(ARM_TENANT_ID)
                    STACK: ${{variables.STACK}}
        
#      - job: infrastructure
#        pool:
#          vmImage: "ubuntu-16.04"
#        steps:
#          - script: |
#              chmod +x scripts/*.sh
#              ./scripts/run-pulumi.sh
#            displayName: "Install pulumi and run pulumi up"
#            name: pulumi
#           env:
#              PULUMI_ACCESS_TOKEN: $(PULUMI_ACCESS_TOKEN)
#              ARM_CLIENT_ID: $(ARM_CLIENT_ID)
#              ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
#              ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
#              ARM_TENANT_ID: $(ARM_TENANT_ID)
#              STACK: ${{variables.STACK}}
