# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - develop

pool:
  vmImage: "ubuntu-latest"

variables:
  ${{ if or(eq(variables['Build.SourceBranchName'], 'develop'), endsWith(variables['System.PullRequest.TargetBranch'], 'develop') ) }}:
  - name: STACK
    value: dev
  ${{ if or(eq(variables['Build.SourceBranchName'], 'master'), endsWith(variables['System.PullRequest.TargetBranch'], 'master') ) }}:
  - name: STACK
    value: prod
  - group: common


stages:
  - stage: preview
    displayName: Preview infra
    jobs:
      - job: previewInfra
        displayName: Preview infra (pulumi)
        cancelTimeoutInMinutes: 7
        steps:
          - task: Npm@1
            displayName: infra - npm install
            inputs:
              command: install
              workingDir: "/"
          - task: Pulumi@1
            displayName: infra - pulumi preview
            inputs:
              azureSubscription: "Azure thesis resource manager"
              command: "preview"
              cwd: "/"
              stack: "$(STACK)"

  - stage: deploy
    displayName: Apply infra (Pulumi up)
    dependsOn: preview
    jobs:
      - job: infrastructure

        pool:
          vmImage: "ubuntu-16.04"
        steps:
          - script: |
              chmod +x infra/scripts/*.sh
              ./scripts/run-pulumi.sh
            displayName: "Install pulumi and run pulumi up"
            name: pulumi
            env:
              PULUMI_ACCESS_TOKEN: $(PULUMI_ACCESS_TOKEN)
              ARM_CLIENT_ID: $(ARM_CLIENT_ID)
              ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
              ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(ARM_TENANT_ID)
              STACK: $(STACK)
