trigger:
  - develop
pr:
  branches:
    include:
      - "*"

stages:
  - stage: setEnvironment
    displayName: Set environment
    jobs:
      - job: setEnv
        displayName: Set environment
        steps:
          - script: |
              if [[ "$(Build.SourceBranchName)" == "develop" || "$(System.PullRequest.TargetBranch)" == "develop" ]]
              then
                echo "##vso[task.setvariable variable=STACK;isOutput=true]dev"
              elif [[ "$(Build.SourceBranchName)" == "master" || "$(System.PullRequest.TargetBranch)" == "master" ]]
              then
                echo "##vso[task.setvariable variable=STACK;isOutput=true]prod"
              fi
            name: setEnv

  - stage: preview
    displayName: Preview infra
    variables:
      - group: common
      - name: STACK
        value: $[ stageDependencies.setEnvironment.setEnv.outputs['setEnv.STACK'] ]
    jobs:
      - job: previewInfra
        displayName: Preview infra (pulumi)
        steps:
          - task: Npm@1
            displayName: Pulumi npm install
            inputs:
              command: install
          - task: Pulumi@1
            displayName: Pulumi infra preview
            inputs:
              azureSubscription: "Azure thesis resource manager"
              command: "preview"
              stack: $(STACK)

  - stage: "deployDev"
    displayName: "Deploy to dev"
    dependsOn: preview
    condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'develop'))
    jobs:
      - template: "azure-pipelines.deploy.yaml"
        parameters:
          commonVariablesGroup: "common"
          environment: "infra-dev"
          stack: "dev"

  - stage: "deployProd"
    displayName: "Deploy to prod"
    dependsOn: preview
    condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))
    jobs:
      - template: "azure-pipelines.deploy.yaml"
        parameters:
          commonVariablesGroup: "common"
          environment: "infra-prod"
          stack: "prod"
