trigger:
  branches:
    include:
      - develop
      - master
pr:
  branches:
    include:
      - "*"

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: setEnvironment
    displayName: Set environment
    jobs:
      - job: setEnv
        displayName: Preview infra (pulumi)
        cancelTimeoutInMinutes: 7
        steps:
          - script: |
              if [[ "$(Build.SourceBranchName)" == "master" || "$(System.PullRequest.TargetBranch)" == "master" ]]
              then
                echo "##vso[task.setvariable variable=ENVIRONMENT;isOutput=true]infra-prod"
                echo "##vso[task.setvariable variable=STACK;isOutput=true]prod"
              fi
              if [[ "$(Build.SourceBranchName)" == "develop" || "$(System.PullRequest.TargetBranch)" == "develop" ]]
              then
                echo "##vso[task.setvariable variable=ENVIRONMENT;isOutput=true]infra-dev"
                echo "##vso[task.setvariable variable=STACK;isOutput=true]dev"
              fi
            name: setEnv

  - stage: preview
    displayName: Preview infra
    variables:
      - group: common
      - name: ENVIRONMENT
        value: $[ stageDependencies.setEnvironment.setEnv.outputs['setEnv.ENVIRONMENT'] ]
      - name: STACK
        value: $[ stageDependencies.setEnvironment.setEnv.outputs['setEnv.STACK'] ]

    jobs:
      - job: previewInfra
        displayName: Preview infra (pulumi)
        cancelTimeoutInMinutes: 7
        steps:
          - script: |
              echo $(STACK)
              echo $(ENVIRONMENT)
              echo $(System.PullRequest.TargetBranch)
              echo $(Build.SourceBranchName)
          - task: Npm@1
            displayName: Pulumi npm install
            inputs:
              command: install
          - task: Pulumi@1
            displayName: Pulumi infra preview
            inputs:
              azureSubscription: "Azure thesis resource manager"
              command: "preview"
              stack: $(STACK)

  - stage: deploy
    displayName: Deploy infra (pulumi)
    dependsOn: preview
    condition: ${{or( eq(variables['Build.SourceBranchName'], 'develop'), eq(variables['Build.SourceBranchName'], 'master') )}}
    variables:
      - group: common
      - name: ENVIRONMENT
        value: $[ stageDependencies.setEnvironment.setEnv.outputs['setEnv.ENVIRONMENT'] ]
      - name: STACK
        value: $[ stageDependencies.setEnvironment.setEnv.outputs['setEnv.STACK'] ]

    jobs:
      - deployment: pulumiUp
        displayName: Run pulumi up
        variables:
          - group: common
          - name: ENVIRONMENT
            value: $[ stageDependencies.setEnvironment.setEnv.outputs['setEnv.ENVIRONMENT'] ]
          - name: STACK
            value: $[ stageDependencies.setEnvironment.setEnv.outputs['setEnv.STACK'] ]
        environment: ${{variables.ENVIRONMENT}}
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - script: |
                      echo $(STACK)
                      echo $(ENVIRONMENT)
                      echo $(System.PullRequest.TargetBranch)
                      echo $(Build.SourceBranchName)
                - task: Npm@1
                  displayName: Pulumi npm install
                  inputs:
                    command: install
                - task: Pulumi@1
                  displayName: Pulumi up ($(ENVIRONMENT))
                  inputs:
                    azureSubscription: "Azure thesis resource manager"
                    command: "up"
                    args: --yes
                    stack: $(STACK)
