parameters:
  - name: commonVariablesGroup
    type: string

  - name: environment
    type: string

  - name: stack
    type: string

jobs:
  - deployment: deployInfra
    displayName: "Deploy infra"
    variables:
      - group: ${{ parameters.commonVariablesGroup }}
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - script: echo ${{ parameters.stack }}
            - checkout: self
            - task: Npm@1
              displayName: Pulumi npm install
              inputs:
                command: install
            - task: Pulumi@1
              displayName: Pulumi up
              inputs:
                azureSubscription: "Azure thesis resource manager"
                command: "up"
                args: --yes
                stack: ${{ parameters.stack }}
